import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

interface BusinessPlanData {
  title: string;
  description: string;
  version: number;
  status: string;
  executive_summary: string;
  market_analysis: string;
  competitive_analysis: string;
  marketing_strategy: string;
  operations_plan: string;
  financial_projections: string;
  funding_requirements: number | null;
  created_at: string;
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#3b82f6',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#1f2937',
  },
  subtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 12,
  },
  metadata: {
    fontSize: 10,
    color: '#9ca3af',
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 10,
    color: '#1f2937',
    pageBreakBefore: 'avoid',
  },
  sectionContent: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#374151',
    textAlign: 'justify',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 20,
    right: 40,
    fontSize: 10,
    color: '#9ca3af',
  },
  footer: {
    marginTop: 40,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    fontSize: 9,
    color: '#9ca3af',
    textAlign: 'center',
  },
});

interface BusinessPlanPDFProps {
  plan: BusinessPlanData;
}

export const BusinessPlanPDF = ({ plan }: BusinessPlanPDFProps) => {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  const formatCurrency = (amount: number | null) => {
    if (!amount) return 'Not specified';
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  return (
    <Document>
      {/* Title Page */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{plan.title}</Text>
          <Text style={styles.subtitle}>{plan.description}</Text>
          <Text style={styles.metadata}>Version {plan.version}</Text>
          <Text style={styles.metadata}>Status: {plan.status}</Text>
          <Text style={styles.metadata}>Created: {formatDate(plan.created_at)}</Text>
          <Text style={styles.metadata}>Funding Goal: {formatCurrency(plan.funding_requirements)}</Text>
        </View>

        <View style={{ marginTop: 40 }}>
          <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 10, color: '#3b82f6' }}>
            Business Plan Summary
          </Text>
          <Text style={styles.sectionContent}>
            This comprehensive business plan outlines the strategic direction, market opportunity, competitive landscape, and financial projections for {plan.title}.
          </Text>
        </View>

        <View style={styles.footer}>
          <Text>Generated by Auto-CEO</Text>
          <Text>{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</Text>
        </View>
      </Page>

      {/* Executive Summary */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={styles.sectionContent}>{plan.executive_summary}</Text>
        <Text style={styles.pageNumber}>Page 1</Text>
      </Page>

      {/* Market Analysis */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Market Analysis</Text>
        <Text style={styles.sectionContent}>{plan.market_analysis}</Text>
        <Text style={styles.pageNumber}>Page 2</Text>
      </Page>

      {/* Competitive Analysis */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Competitive Analysis</Text>
        <Text style={styles.sectionContent}>{plan.competitive_analysis}</Text>
        <Text style={styles.pageNumber}>Page 3</Text>
      </Page>

      {/* Marketing Strategy */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Marketing Strategy</Text>
        <Text style={styles.sectionContent}>{plan.marketing_strategy}</Text>
        <Text style={styles.pageNumber}>Page 4</Text>
      </Page>

      {/* Operations Plan */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Operations Plan</Text>
        <Text style={styles.sectionContent}>{plan.operations_plan}</Text>
        <Text style={styles.pageNumber}>Page 5</Text>
      </Page>

      {/* Financial Projections */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Financial Projections</Text>
        <Text style={styles.sectionContent}>{plan.financial_projections}</Text>
        <Text style={styles.pageNumber}>Page 6</Text>
      </Page>
    </Document>
  );
};
